vtex-apps/wish-list

CHANGELOG.md
react/package.json
react/utils/normalize.js
react/yarn.lock

Fix broken link at the product-context

Adding LinkText to the product context

---

CHANGELOG.md
docs/README.md
manifest.json
messages/context.json
messages/en.json
messages/es.json
react/MyAccountWishlistLink.tsx
store/blocks.json
store/interfaces.json
store/plugins.json

Added Wishlist under My Account menu
[Workspace](https://wishlist--sandboxusdev.myvtex.com/account#/wishlist)

Adding Wishlist menu under My Account

---

CHANGELOG.md
manifest.json
react/MyAcccountWishlistPage.tsx
store/blocks.json
store/interfaces.json

https://brenowish--sandboxusdev.myvtex.com/account#/wishlist

Fix My Account page rendering

---

CHANGELOG.md
docs/README.md
react/AddProductBtn.tsx
react/queries/productById.gql
react/utils/normalize.js

- Message after adding to the wishlist now has a link to the `/account/#wishlist` page
- Missing seller's additional information from GraphQL search

Fixing graphql query

---

CHANGELOG.md
messages/it.json

Adding Italian translation

---

CHANGELOG.md
docs/README.md
react/MyAccountWishlistLink.tsx
store/blocks.json
store/interfaces.json
store/plugins.json

- Allow the store to define their blocks structure under My Account

Removing plugins from the app to allow the store to define its blocks

---

CHANGELOG.md
react/AddProductBtn.tsx
react/ProductSummaryWishlist.tsx

- Add product after login
- Products recently added from the shelf don't show up as wishlisted at the PDP
- Products not showing up correctly when store uses the new search-resolver

[WISHLIST-1] Fixes search-resolver issue with wrong productId

---

CHANGELOG.md
admin/navigation.json
admin/routes.json
dotnet/Controlers/RoutesController.cs
dotnet/Data/IWishListRepository.cs
dotnet/Data/WishListRepository.cs
dotnet/service.json
manifest.json
messages/context.json
messages/en.json
messages/es.json
messages/pt.json
react/WishlistAdmin.tsx
react/package.json
react/tsconfig.json
react/yarn.lock

- Added ability to download all user wishlists as an xls file
- The most recent version is installed at [https://sandboxusdev.myvtex.com/](url).
- Navigate to admin -> products -> catalog -> wishlist

Wishlist Download

---

CHANGELOG.md
react/AddProductBtn.tsx
react/ProductSummaryWishlist.tsx

- At PDP, heart stays filled when changing to another product from the shelf
- No SSR

State persistence

---

CHANGELOG.md
react/AddProductBtn.tsx

Once added, cannot remove from wishlist

---

CHANGELOG.md
react/AddProductBtn.tsx

- Cannot remove from Wishlist immediately after adding it

Cannot remove an item immediately after adding it

---

CHANGELOG.md
react/AddProductBtn.tsx
react/WishlistAdmin.tsx
react/queries/productById.gql
react/utils/normalize.ts

[WISHLIST-6] Adding Spotprice to the product context

---

CHANGELOG.md
react/AddProductBtn.tsx
react/ProductSummaryWishlist.tsx

- Update wishlist to display correct sku variation

Wishlist SKU Display

---

CHANGELOG.md
docs/README.md
react/ProductSummaryWishlist.tsx
react/WishlistEmpty.tsx
store/interfaces.json

Good morning team, I wanted to comment that I was asked to make a custom view in case there are no products in the wish list. If you could help me with this functionality.
In the image you can see the custom view that the store needs to display a message in case there are no products.

Custom view in case you do not add any product to the wish list

---

CHANGELOG.md
dotnet/Data/WishListRepository.cs
dotnet/GraphQL/Query.cs
dotnet/Services/WishListService.cs
manifest.json

Added policy to fix inability to apply db schema

---

CHANGELOG.md
docs/README.md

What problem is this solving?
Improve README file, added URL information in README file for the user
How to test it?
Please look at the README file

[WISHLIST-35] Improve README

---

CHANGELOG.md
dotnet/Data/WishListRepository.cs
dotnet/GraphQL/Query.cs
react/AddProductBtn.tsx
react/ProductSummaryWishlist.tsx

What does this PR do?
Set the shopperId as the required field for GetWishList to prevent empty shopperId passed

[WISHLIST-41] set shopperId required

---

.eslintrc
CHANGELOG.md
admin/navigation.json
cypress/.eslintrc
docs/README.md
dotnet/Data/IWishListRepository.cs
dotnet/Data/WishListRepository.cs
dotnet/GraphQL/Types/CheckListType.cs
dotnet/Models/ValidateToken.cs
dotnet/Models/ValidatedUser.cs
dotnet/Services/IWishListService.cs
dotnet/Services/WishListService.cs
graphql/schema.graphql
react/AddProductBtn.tsx
react/ProductSummaryWishlist.tsx
react/WishlistAdmin.tsx

Q3 App Review 
followed instructions here: https://www.notion.so/vtexhandbook/2022-Q3-App-Review-Checklist-a68487945f864ce0a2b216a43d31efa3
- GraphQL mutation security.
- Logging optimization.
[Workspace](https://aurora--lojausereserva.myvtex.com/account#/wishlist)

[WISHLIST-58] App review

---

CHANGELOG.md
dotnet/GraphQL/Query.cs
dotnet/GraphQL/Types/ListItemsType.cs
dotnet/GraphQL/Types/WishListWrapperType.cs
dotnet/Services/IWishListService.cs
dotnet/Services/WishListService.cs
graphql/schema.graphql
react/WishlistAdmin.tsx
react/queries/exportList.gql

What problem is this solving?
Added exportList graphql and for the download feature to prevent data leak
How to test it?
[Workspace](https://aurora--jefferspet.myvtex.com/admin/wishlist)

WISHLIST exportList graphql

---

CHANGELOG.md
cypress/integration/2.1-graphql_testcases.spec.js
cypress/integration/2.2-api_testcases.spec.js
cypress/support/api_testcase.js
cypress/support/graphql_testcase.js
cypress/support/selectors.js
cypress/support/utils.js
cypress/support/wishlist.js

- added export list graphql and removed readwishlist data API
#changingTooling

 [ENGINEERS-1094] - added export list graphql and removed readwishlist data API

---

CHANGELOG.md
react/utils/normalize.ts

Fixes the eror when skuSpecification is null
[https://cris1--toffro.myvtex.com/geanta-vlogo-2w2b0j20kgw46r/p](https://cris1--toffro.myvtex.com/geanta-vlogo-2w2b0j20kgw46r/p)
Add this product to the wishlist and navigate to the wishlist page

setting skuSpecification to empty array if it's null

---

CHANGELOG.md
react/AddProductBtn.tsx

Fixes error on GA event, which was sent with undefined selectedItem.
Error appears in console of browser.
Environment with fix: https://leo--italiaonline.myvtex.com/epson-wf-6xxx-ink-cartridge-black-xxl-103096/p

GA event error occurring when adding product to wish list on PDP

---

CHANGELOG.md
react/AddProductBtn.tsx

-Fix null pointer exception
- GA event error due to undefined selectedItem

Fix null pointer exception

---

CHANGELOG.md
dotnet/Data/IWishListRepository.cs
dotnet/Data/WishListRepository.cs
dotnet/GraphQL/Query.cs
dotnet/Services/IWishListService.cs
dotnet/Services/WishListService.cs
graphql/schema.graphql
react/queries/listSize.gql

Add Admin permission

---

dotnet/Data/IWishListRepository.cs
dotnet/Data/WishListRepository.cs
dotnet/GraphQL/Query.cs
dotnet/Services/IWishListService.cs
dotnet/Services/WishListService.cs
graphql/schema.graphql
manifest.json
messages/en.json
messages/es.json
messages/pt.json
react/WishlistAdmin.tsx
react/queries/exportListPaged.gql
react/queries/listSize.gql

Feature: add split export data when is long

Feature: Long exporlist

---

dotnet/GraphQL/Query.cs
dotnet/Services/WishListService.cs

Feature: Get  VtexIdclientAutCookie cookie

Feature: Get  VtexIdclientAutCookie cookie

---

dotnet/Services/WishListService.cs

Fix: authetications in mutations

Fix: authetications in mutations

---

CHANGELOG.md
messages/hu.json

It relates to the task [LOC-14704](https://vtex-dev.atlassian.net/browse/LOC-14704). 
[LOC-14704]: https://vtex-dev.atlassian.net/browse/LOC-14704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Hungarian translations

---

CHANGELOG.md
dotnet/Services/WishListService.cs

validate shopperID Email or UserID

validate shopperID Email or UserID
